version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    restart: unless-stopped
    command: python -m chainlit run app.py -w --host 0.0.0.0 --port 7860